name: Latest Medium Blog Posts
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in Medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@piyushrajyadav28"
          max_post_count: 5
          template: "$newline- [$title]($url)$newline"
          committer_username: "blog-post-bot"
          committer_email: "blog-post-bot@example.com"
          commit_message: "Updated with latest Medium blog posts"
          date_format: "mmm dd, yyyy"
